// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  if (!$ || !shdr || !shdr.App) {
    console.warn("Unable to start Shdr, please load required libraries first.");
  } else {
    $(function() {
      return _this.app = new shdr.App("editor", "viewer");
    });
  }

}).call(this);
