// Generated by CoffeeScript 1.4.0
(function() {
  var Models;

  Models = {
    'models/hexmkii.js': {
      name: 'Hex MKII',
      scale: 0.01
    },
    'models/monkey_low.js': {
      name: 'Monkeyhead (low)'
    },
    'models/monkey_mid.js': {
      name: 'Monkeyhead (mid)'
    },
    'models/monkey_high.js': {
      name: 'Monkeyhead (high)'
    }
  };

  this.shdr || (this.shdr = {});

  this.shdr.Models = Models;

}).call(this);
