// Generated by CoffeeScript 1.4.0
(function() {
  var Models;

  Models = {
    'models/cube.js': {
      name: 'Cube'
    },
    'models/sphere.js': {
      name: 'Shere'
    },
    'models/torus.js': {
      name: 'Torus'
    },
    'models/dragon.js': {
      name: 'Dragon',
      scale: 1.2
    },
    'models/hexmkii.js': {
      name: 'Hex MKII',
      scale: 0.01
    },
    'models/suzanne_low.js': {
      name: 'Suzanne (low)'
    },
    'models/suzanne_high.js': {
      name: 'Suzanne (high)'
    }
  };

  this.shdr || (this.shdr = {});

  this.shdr.Models = Models;

}).call(this);
