// Generated by CoffeeScript 1.4.0
(function() {
  var Storage;

  Storage = (function() {

    function Storage() {}

    Storage.available = 'localStorage' in window;

    Storage.list = function() {
      if (!Storage.available) {
        return [];
      }
      return localStorage.data;
    };

    Storage.add = function(name, obj, overwrite) {
      var key;
      if (overwrite == null) {
        overwrite = true;
      }
      if (!Storage.available) {
        return false;
      }
      if (name in localStorage.data && !overwrite) {
        return false;
      }
      key = name + "";
      localStorage.data[key] = obj;
      return true;
    };

    Storage.get = function(name) {
      if (!Storage.available || !name in localStorage.data) {
        return null;
      }
      return localStorage.data[name];
    };

    Storage.clear = function() {
      if (!Storage.available) {
        return;
      }
      return localStorage['data'] = {};
    };

    Storage.clearSettings = function() {
      if (!Storage.available) {
        return;
      }
      return localStorage['settings'] = {};
    };

    return Storage;

  })();

  if (Storage.available) {
    if (!'settings' in localStorage) {
      Storage.clearSettings();
    }
    if (!'data' in localStorage) {
      Storage.clear();
    }
  }

  this.shdr || (this.shdr = {});

  this.shdr.Storage = Storage;

}).call(this);
